# Generated by Django 5.0.3 on 2024-03-17 00:49

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_type', models.CharField(choices=[('laptop', 'Laptop'), ('desktop', 'Desktop'), ('phones', 'Phones'), ('other', 'Other')], default='other', max_length=100)),
                ('brand', models.CharField(choices=[('hp', 'Hp'), ('acer', 'Acer'), ('apple', 'Apple'), ('dell', 'Dell'), ('asus', 'Asus'), ('samsung', 'Samsung'), ('infinix', 'Infinix'), ('lg', 'Lg'), ('sony', 'Sony'), ('other', 'Other')], default='other', max_length=100)),
                ('category', models.CharField(choices=[('computers', 'Computers'), ('mobile Phones', 'Mobile Phones'), ('other', 'Other')], default='Other', max_length=100)),
                ('pid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnop1234567890', length=5, max_length=40, prefix='PID-', primary_key=True, serialize=False)),
                ('sku', shortuuid.django_fields.ShortUUIDField(alphabet='ABCDEFG1234567890', length=5, max_length=10, prefix='SKU-', unique=True)),
                ('quantity', models.IntegerField()),
                ('available_qty', models.IntegerField()),
                ('production_date', models.DateField()),
                ('addded_on', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='store.product')),
                ('restock_level', models.IntegerField()),
                ('low_stock_alert', models.BooleanField(default=False)),
                ('last_restock_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='other', max_length=200)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('order_id', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnop1234567890', length=5, max_length=10, prefix='OID-', unique=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
